### ISSUE TITLE
Declarative backref rels not filtering by polymorphic identity

### ISSUE THREAD

**Issue by revmischa** [mitsuhiko/flask-sqlalchemy#492] opened 2017-04-05 23:30 UTC
More info here:
https://bitbucket.org/zzzeek/sqlalchemy/issues/3960/declarative-backref-not-filtering-by

"the issue is somewhere in db.Model where their declarative base is interfering with declarative being able to set the "single inheritance" flag on the Event1 mapper."

**Comment by zzzeek** [comment] 2017-04-05 23:57
likely because __tablename__ is set to non-None in all cases now: https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L641    that should be None to indicate single inheritance.

**Comment by revmischa** [comment] 2017-04-06 00:11
@zzzeek it should be unset on the "base" classes, but set on the "child" classes? to the same thing?

**Comment by zzzeek** [comment] 2017-04-06 00:40
whichever class should have its own table gets __tablename__, whichever subclass that's single inh either should not have __tablename__ at all (declarative looks in cls.__dict__ to check that the attribute is local to a certain class) or it should return None - declarative then sets that mapper as single=True.

Basically the way db.Model here wants to do __tablename__, if it has that feature then you need to set __tablename__ = None on your model.

**Comment by davidism** [comment] 2017-04-06 01:48
I'm working on fixing the tablename loguc, I'll keep this example in mind.

**Comment by mark-anders** [comment] 2017-09-12 14:20
Btw, the title of the bug is incorrect: it doesn't really involve relationships at all. It is that queries that specify a subclass do not emit a where clause when using polymorphic identity in single table, so effectively, the type is ignored.

Here's an example:


```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column, Integer, String

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
db = SQLAlchemy(app)
app.config['SQLALCHEMY_ECHO'] = True

class Group(db.Model):
    __tablename__ = 'groups'

    group_id = Column(Integer, primary_key=True)
    name = Column(String)
    type = Column(String)

    __mapper_args__ = {
        'polymorphic_on': type,
        'polymorphic_identity': "group",
    }

    def __init__(self, name):
        self.name = name

class OwnerGroup(Group):
    # __tablename__ = None

    __mapper_args__ = {
        'polymorphic_identity': "owner"
    }


class SharedGroup(Group):
    # __tablename__ = None
    __mapper_args__ = {
        'polymorphic_identity': "shared"
    }

db.drop_all()
db.create_all()
session = db.session

o1 = OwnerGroup("#1 owner")
o2 = OwnerGroup("#2 owner")
s = SharedGroup("Shared")
session.add_all([o1,o2,s])
session.commit()
q = session.query(SharedGroup)
print(q)
found = q.all()
assert len(found) == 1, "Found too many SharedGroups"

```

Based on the hint from @zzzeek , if you uncomment the `__tablename__ = None`, it works. 

This seems to be a pretty serious bug.  Hope it gets fixed soon.

**Comment by davidism** [comment] 2017-09-25 20:35
Duplicate of #478. Should be covered by #541, which also adds a test that the query contains the polymorphic condition.

**Closed by davidism** 2017-09-25 20:35 UTC
Labels: tablename
