### ISSUE TITLE
schema for multiple binds

### ISSUE THREAD

**Issue by itajaja** [mitsuhiko/flask-sqlalchemy#494] opened 2017-04-24 19:58 UTC
Hi! how can you specify two different postgres schemas with two different binds? And as a more generic question, in the following code: `SQLAlchemy(app).metadata` refers to the default bind, correct? How can we access/modify the other metadata binds?

**Comment by ThiefMaster** [comment] 2017-04-24 19:59
Schemas have nothing to do with binds (different connections/databases). If you want to use schemas, set it through the table args.

**Comment by itajaja** [comment] 2017-04-24 20:03
I mean a postgres schema. In my opinion it has to do with a connection though, because if I have two binds (connections). it's likely they are going to access to different schemas. if I do 

```
db = SQLAlchemy(app)
db.metadata.schema = 'foo'
```

the foo schema is used in both connections?

**Comment by ThiefMaster** [comment] 2017-04-24 20:07
Why set it on the metadata at all?

**Comment by itajaja** [comment] 2017-04-24 20:10
because it's a great shorthand? otherwise you'd have to set it on every table.

But let's leave the schema thing aside, still there is a one to one relationship between a bind and a metadata object. see http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.MetaData. So the question remains, if you specify multiple binds, what does `SQLAlchemy(app).metadata` returns?

**Comment by davidism** [comment] 2017-04-24 21:02
Duplicate of #222

**Closed by davidism** 2017-04-24 21:02 UTC
