### ISSUE TITLE
Provide a way to configure the SA engine

### ISSUE THREAD

**Issue by Lawouach** [mitsuhiko/flask-sqlalchemy#589] opened 2018-01-28 16:00 UTC
Hi all,

Unless I'm mis-reading the code, there is no way to provide engine creation options. One of them that appears with SA 1.2 is [pool_pre_ping](http://docs.sqlalchemy.org/en/latest/core/pooling.html#pool-disconnects-pessimistic). 

I'm not sure I can provide extra parameters via flask-sqlalchemy parameters. Should I create the engine out of band?

Thanks,

**Comment by davidism** [comment] 2018-01-28 16:19
Duplicate of #525

**Closed by davidism** 2018-01-28 16:19 UTC

**Comment by Lawouach** [comment] 2018-01-28 16:32
Okay, even though this was closed and until something better comes up, here is what I did:

```
from flask_sqlalchemy import SQLAlchemy as SA

class SQLAlchemy(SA):
    def apply_pool_defaults(self, app, options):
        options["pool_pre_ping"] = True

db = SQLAlchemy()
```

**Comment by davidism** [comment] 2018-01-28 16:51
Subclassing is an intended way to extend Flask and its extensions, so that's fine.

**Comment by AnumSheraz** [comment] 2019-11-13 18:08
I spent 4 days trying to get to the bottom of the issue (`Sql server has gone away`), and though `'pool_pre_ping': True` is NOT working properly, but i now realized that the engine_options were not loaded into my db instance. Here is what I was trying to do (as seen in many flask example projects), I was adding these SQLALCHEMY_ENGINE_OPTIONS via configs (shown in [docs)](https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/)

```
class DevConfig():
    ...
    DEBUG = True
    SQLALCHEMY_ENGINE_OPTIONS = {'pool_recycle': 280, 'pool_timeout': 100, 'pool_pre_ping': True}
    SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI_DEV')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
```

and using these configs when init app 

```
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()

instance_name = os.environ.get("FLASK_ENV", "dev")
app = create_app(app_config[instance_name])
# --------
def create_app(config):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config)

    # INIT DATABASE
    db.init_app(app)
    with app.app_context():
        db.create_all()
```
I thought this would work, but it didn't. Finally @Lawouach answer worked fine.

**Comment by ssharma94** [comment] 2019-12-26 01:24
> apply_pool_defaults
Thanks for the snippet @Lawouach 
I had issues running that code. The error I was getting `apply_pool_defaults() takes 3 positional arguments but 4 were given`
 The below one worked for me:
`class SQLAlchemy(_BaseSQLAlchemy):
    def apply_pool_defaults(self, app, options):
        super(SQLAlchemy, self).apply_pool_defaults(app, options)
        options["pool_pre_ping"] = True`

**Comment by zmarffy** [comment] 2020-01-13 05:29
These solutions do not work for me. They do not seem to have any effect. Shouldn't the `options` be updated before `super` is called?

**Comment by BasicExp** [comment] 2020-09-11 19:10
We were experiencing the following error when using MySQL (pymysql) with Flask/SQLAlchemy

```
(pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')
```

We found that the combination configuration of the following worked for us, eliminating the error entirely. Mostly mentioning the error here so anyone who suffers from a similar issue will find this thread easily.

```
from flask_sqlalchemy import SQLAlchemy as _BaseSQLAlchemy

class SQLAlchemy(_BaseSQLAlchemy):
    def apply_pool_defaults(self, app, options):
        super(SQLAlchemy, self).apply_pool_defaults(app, options)
        options["pool_pre_ping"] = True

db = SQLAlchemy()
 ```

```
app.config['SQLALCHEMY_POOL_RECYCLE'] = 28000
app.config['SQLALCHEMY_POOL_TIMEOUT'] = 20000
app.config['SQLALCHEMY_POOL_SIZE'] = 10
app.config['SQLALCHEMY_MAX_OVERFLOW'] = 0
```
