### ISSUE TITLE
Problem with STI: __tablename__ automatically set (unwanted behaviour)

### ISSUE THREAD

**Issue by dizpers** [mitsuhiko/flask-sqlalchemy#481] opened 2017-03-03 06:09 UTC
Hey, guys.

I'm using:

* Flask-SQLAlchemy==2.2;
* SQLAlchemy==1.1.5.

And have the problem, originally described in [this SO question](http://stackoverflow.com/questions/42563434/sqlalchemy-using-sti-how-to-automatically-substitute-type-field/42567228#42567228). My models setup looks like the following:

```python
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class Item(db.Model):
    __tablename__ = 'item'

    id = db.Column(db.Integer, primary_key=True)
    info = db.Column(db.String(255))
    type = db.Column(db.String())

    __mapper_args__ = {
        'polymorphic_on': type
    }


class ItemA(Item):
    __mapper_args__ = {
        'polymorphic_identity': 'a'
    }


class ItemB(Item):
    __mapper_args__ = {
        'polymorphic_identity': 'b'
    }


class ItemC(Item):
    __mapper_args__ = {
        'polymorphic_identity': 'c'
    }

print(ItemB.query)
```

I want to use [Single Table Inheritance](http://docs.sqlalchemy.org/en/latest/orm/inheritance.html#single-table-inheritance) (STI). So expected output of the `print(ItemB.query)` statement is something like:

```SQL
SELECT item.id AS item_id, item.info AS item_info, item.type AS item_type FROM item WHERE item.type IN (?)
```

And at the same time I'm getting:

```SQL
SELECT item.id AS item_id, item.info AS item_info, item.type AS item_type FROM item
```

[@univerio](http://stackoverflow.com/users/341730/univerio) (@univerio, is it you? 😃 ) has pointed that Flask-SQLAlchemy automatically set `__tablename__` attribute. It means that my model setup, presented above, doesn't follow STI model.

**Is there any way to disable such behaviour by default?** From my POV that behaviour sounds like a wrong approach, having a developer (how doesn't know that fact) to spend hours to understand why something isn't working.

Thanks.

**Comment by dizpers** [comment] 2017-03-03 06:17
BTW, I've just noted that it's happening only with **Flash-SQLAlchemy==2.2** (no problems at all with **2.1** version).

**Comment by davidism** [comment] 2017-03-03 14:27
This is odd, because the tests for single table inheritance pass. I'll add it to the 2.2.1 milestone.

**Comment by dizpers** [comment] 2017-03-04 10:06
I've just discovered that it becames broken on https://github.com/mitsuhiko/flask-sqlalchemy/commit/f4662ad464a73befa47cf74754fdbfe156570e59.

**Comment by dizpers** [comment] 2017-03-04 11:05
@davidism, I've just comitted the test for single table inheritance setup (https://github.com/dizpers/flask-sqlalchemy/commit/d75506b77a99555779cfa9ec54a35d8da0b83f5b). It checks that `__table__` and `__tablename__` is None for child models. I thought that this should be the expected behaviour for some cases (I would say STI only for now).

And in the meantime there are 2 facts:
1. it was working with **Flask-SQLAlchemy==2.1** (last working commit is 9eff8b6597987c9ac4ae86d8672d5abf9f8e4312), `__table__` and `__tablename__` attributes were in child models;
2. futher more with raw **SQLAlchemy** it works just fine and also has those attributes  (please, check https://repl.it/GFDD/2).

So, it seems that problem is somewhere else (than just `__table__` and `__tablename__` values).

**Comment by Natureshadow** [comment] 2017-05-05 19:34
The Veripeditus team and I just spent a full month finding out why everything broke all over the place, and it turned out to be this very bug, which breaks not only single table inheritance, but also joined table inheritance in our case (but that might be because we configure the polymorphic mapper with some advanced magic).

**Comment by vToMy** [comment] 2017-05-06 09:49
I believe I have a solution for this. I changed the [__tablename__](https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L642) definition as follows:
```
    @declared_attr
    def __tablename__(cls):
        if '_cached_tablename' not in cls.__dict__:
            if _should_set_tablename(cls):
                cls._cached_tablename = camel_to_snake_case(cls.__name__)
            else:
                cls._cached_tablename = None

        return cls._cached_tablename
```

The noticeable difference is that I explicitly set `_cached_tablename ` to `None` if `__should_set_tablename` returns `False`. The reason being that, otherwise, the model uses the inherited cached name which caused this wrong behavior.

**Comment by davidism** [comment] 2017-09-25 20:34
Duplicate of #478, although a slightly different error somehow.

**Closed by davidism** 2017-09-25 20:34 UTC
Labels: bug, tablename
