### ISSUE TITLE
Bind works only for same schema name

### ISSUE THREAD

**Issue by whitish** [mitsuhiko/flask-sqlalchemy#347] opened 2015-11-09 21:41 UTC
I want to create my model in two different databases (e.g., in Postgres and Redshift) with different shema names. E.g., in postgres i have schema _public_, and in redshift schema called _data_.

E.g., I have two engines:

``` python
SQLALCHEMY_BINDS = {
    'mypublic':   app.config['SQLALCHEMY_DATABASE_URI'],
    'data': 'redshift+psycopg2://dbuser:pass@dbhost.redshift.amazonaws.com:5439/mydb'
}
```

Here is a model:

``` python
class Campaign(Base):
    __tablename__ = 'campaign'
    #__bind_key__ = 'data'
    campaignid = Column(Integer, primary_key=True)
    campaign_name = Column(String(120))
    smth = Column(BigInteger)
```

First, I tried to create declarative base and bind it explicitly (which works good but doesn't solve my problem 'cos I need to define model twice for each schema):

``` python
engine = create_engine('redshift+psycopg2://dbuser:pass@dbhost.redshift.amazonaws.com:5439/mydb')
Base = declarative_base()
Base.metadata = MetaData(bind=engine, schema='data')
Base.metadata.create_all(bind=engine)
```

But what I expect to do with binds is to use same model and create it in different schemas on different DBs. So I can use _**bind_key**_ to indicate which DB i want to use but also indicate what **schema names** for different DBs though.

Appreciate for any hints.

**Comment by kblomqvist** [comment] 2016-05-01 06:39
I think you shouldn't add the base db into the binds. Instead set only data into the binds and leave the public to be default (`binds=None`).

```python
SQLALCHEMY_DATABASE_URI = "..."
SQLALCHEMY_BINDS = {
    'data': 'redshift+psycopg2://dbuser:pass@dbhost.redshift.amazonaws.com:5439/mydb'
}
```

Now when you want your model to be committed into the public db just don't specify the `__bind_key__` (equals to `None`). And when you want to use data db then set `__bind_key__="data"`.

**Comment by davidism** [comment] 2017-04-24 21:02
Duplicate of #222

**Closed by davidism** 2017-04-24 21:02 UTC
