### ISSUE TITLE
`init_app` should set `self.app`

### ISSUE THREAD

**Issue by matthewstory** [mitsuhiko/flask-sqlalchemy#607] opened 2018-03-14 00:13 UTC
I have just moved to a deferred app initialization and was greeted with the following error

```
>>> db.init_app(app)
>>> db.get_app()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Flask_SQLAlchemy-2.3.2-py3.5.egg/flask_sqlalchemy/__init__.py", line 912, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
```

The docs (or at least my understanding of them) suggest that this should work. The issue seems to be that `self.app` is only assigned in `__init__`, rather than being assigned by `init_app`. Happy to supply a fix if there is agreement this is a bug.

**Comment by greyli** [comment] 2018-03-14 00:24
There is [a chapter about the context](http://flask-sqlalchemy.pocoo.org/2.3/contexts/) in the documentation. Besides, you may try to run the shell with `flask shell`, it will activate an application context for you.

**Comment by matthewstory** [comment] 2018-03-14 00:38
Yes this is the set of docs I was reading earlier. It's clear from the `test_no_app_bound` that this behavior is by design, I guess I just don't get why we woudln't set the `app` in `init_app` if it's not been set previously.

The particular use-case for me right now is in my model tests. My models are built in such a way as to not rely on the flask context in any way, so my tests do no setup or teardown of the flask state because until this point they haven't had to. I have currently worked around this by manually assigning `db.app`.

**Comment by greyli** [comment] 2018-03-14 01:17
In short, this pattern supports multiple applications running in the same Python process. Here is a note comes from [Flask's docs](http://flask.pocoo.org/docs/0.12/extensiondev/).

> Note on init_app
> As you noticed, init_app does not assign app to self. This is intentional! Class based Flask extensions must only store the application on the object when the application was passed to the constructor. This tells the extension: I am not interested in using multiple applications.
> 
> When the extension needs to find the current application and it does not have a reference to it, it must either use the current_app context local or change the API in a way that you can pass the application explicitly.

**Comment by davidism** [comment] 2018-03-14 01:55
Duplicate of a bunch of other issues.

**Closed by davidism** 2018-03-14 01:55 UTC
