### ISSUE TITLE
_should_set_tablenames ignores __tablename__ attribute in base class if model has a primary key

### ISSUE THREAD

**Issue by dusktreader** [mitsuhiko/flask-sqlalchemy#428] opened 2016-09-08 23:41 UTC
I have defined a class-level property* for the __tablename__ function so that I can utlize the tableize method from the inflection package. However, this property is ignored by flask-sqlalchemy since my model has a primary key. So, instead of searching for a __tablename__ attribute in a base class (which is available), _should_set_tablenames returns true and sets the tablename using flask-sqlalchemy's pattern. Is the enforcement when a primary key exists to aid in automatic naming for sqlalchemy inheritance?

 I need a mechanism to specify how the tablename should be coerced from the model name, but can't find a good way to do it

*code for classproperty:
```
class classproperty(property):
    """
    This defines a decorator that can be used to describe a read-only property
    that is attached to the class itself instead of an instance.
    """

    def __get__(self, cls, owner):
        return classmethod(self.fget).__get__(None, owner)()
```

**Comment by davidism** [comment] 2016-09-09 02:11
Duplicate of #349 and #323, although you wouldn't use a class-level property for this anyway, you'd use `declared_attr`.

**Closed by davidism** 2016-09-09 02:11 UTC

**Comment by dusktreader** [comment] 2016-09-09 03:00
@davidism thanks for the heads up about declared_attr
