### ISSUE TITLE
GitHub homepage URL links to Flask's docs instead of the extension's.

### ISSUE THREAD

**Issue by untitaker** [mitsuhiko/flask-sqlalchemy#203] opened 2014-06-07 20:44 UTC
![2014-06-07-224358_621x119_scrot](https://cloud.githubusercontent.com/assets/837573/3209738/79ccd3b0-ee84-11e3-920a-2a40216d8497.png)

**Comment by svenstaro** [comment] 2015-01-10 01:21
Duplicate of #65 but this one has pictures!

**Comment by jeffwidman** [comment] 2015-08-07 06:59
Bump. I got confused because first Google result for the docs is the old pythonhosted.org docs for v 0.16, then looked here and didn't immediately see a link to updated docs either... figured it out, but what a mess.

**Comment by immunda** [comment] 2015-11-25 10:04
Fixed :+1:

**Closed by immunda** 2015-11-25 10:04 UTC

**Comment by jeffwidman** [comment] 2015-11-25 10:43
:+1:
